import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'All recipes',
    color: Colors.orange,
  ),
  Category(
    id: 'c2',
    title: 'Breakfast & Brunch',
    color: Colors.orange,
  ),
  Category(
    id: 'c3',
    title: 'Lunch',
    color: Colors.orange
  ),
  Category(
    id: 'c4',
    title: 'Dinner',
    color: Colors.orange,
  ),
  Category(
    id: 'c5',
    title: 'Appetizers & Snacks',
    color: Colors.orange,
  ),
  Category(
    id: 'c6',
    title: 'Salads',
    color: Colors.orange,
  ),
  Category(
    id: 'c7',
    title: 'Side Dishes',
    color: Colors.orange,
  ),
  Category(
    id: 'c8',
    title: 'Healthy',
    color: Colors.orange,
  ),
  Category(
    id: 'c9',
    title: 'Drinks',
    color: Colors.orange,
  ),
  Category(
    id: 'c10',
    title: 'Desserts',
    color: Colors.orange,
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c4',
    ],
    title: 'Smoky Beef and Potato Fry-Up',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/8/82/Smoky_beef_and_potato_fry_up_-_Dinnerly.jpg',
    duration: 30,
    ingredients: [
      '1 potato',
      '1 tomato',
      '1 red onion',
      '250g beef mince',
      '10g smoky barbecue seasoning',
      '50g baby spinach leaves',
      '1 tsp red or white wine vinegar',
      '1 tsp olive oil',
      '2 tsp tomato paste',
      '1 tsp soy sauce',
      '2 eggs',
    ],
    steps: [
      'Prep ingredients: Cut the unpeeled potato into 1cm chunks. Finely chop the onion and tomato. Put 1 tsp red wine vinegar in a bowl, add the tomato and toss to coat. ',
      'Soften potato and onion: Heat 2 tsp olive oil in a medium deep frypan over high heat. Cook the potato and onion, covered, stirring occasionally, for 8-10 mins until the potato is golden. Remove from the pan. Add the beef mince to the pan and cook, breaking up the lumps with a spoon, for 3-4 mins until browned.',
      'Add seasoning: Add the potato mixture to the mince and cook, stirring, for 2 mins. Add the barbecue seasoning, 2 tsp tomato paste and 1 tsp soy sauce and cook, stirring, for 30 secs or until fragrant. Add 60ml (¼ cup) water and cook, stirring, for 2-3 mins until the potato is tender.',
      'Cook eggs: Meanwhile, heat 2 tsp olive oil in a medium frypan over medium heat. Crack 2 eggs into the pan and cook for 3-4 mins until just set or cooked to your liking. Remove the pan from the heat.',
      'Serve up: Stir the spinach into the beef mixture (see Make it yours) and cook for 1 min or until wilted. Remove the pan from the heat. Taste, then season with salt and pepper. Divide the beef mixture among bowls, top with the fried eggs and scatter over the tomato. Enjoy!',
      'Make it yours: Fancy a side salad? Reserve half the spinach and dress with a quick vinaigrette. This could be as simple as olive oil and your favourite vinegar, or add some honey, mustard or crushed garlic for an easy flavour boost.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),

  Meal(
    id: 'm2',
    categories: [
      'c1',
      'c3',
      'c6',
      'c8',
    ],
    title: 'Haloumi Couscous Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://marleyspoon.com/media/recipes/161060/main_photos/large/super_fast_haloumi_couscous_salad-e33d76389c0c2668bbeeca06c68c1186.jpeg',
    duration: 20,
    ingredients: [
      '1 zucchini',
      '1 carrot',
      '180g haloumi',
      '150g couscous',
      '10g Moroccan seasoning',
      '20g dried currants',
      '100g baby spinach leaves',
      '200ml boiling water',
      '2 tsp olive oil',
      '3 tsp red or white wine vinegar',
      '1 garlic clove',
      '1.5 tsp honey',
    ],
    steps: [
      'Prep ingredients: Quarter the zucchini lengthwise, then cut into 1cm chunks. Shred the carrot using a julienne peeler or coarsely grate with a box grater. Crush or finely chop 1 garlic clove. Thinly slice the haloumi.',
      'Soak couscous: Put the couscous in a large heatproof bowl, pour over 200ml boiling water and cover with a plate. Stand for 5 mins or until the water is absorbed. Season with salt and pepper, then fluff the couscous with a fork.',
      'Soften veggies: Meanwhile, heat a drizzle of olive oil in a medium frypan over medium-high heat. Cook the zucchini, stirring, for 5 mins or until slightly softened. Add the carrot and garlic and cook, stirring, for 2 mins. Add half the Moroccan seasoning and cook, stirring, for 1 min or until fragrant. Remove from the pan, reserving the pan.',
      'Cook haloumi: Combine the remaining Moroccan seasoning and a generous drizzle of olive oil in a large bowl. Add the haloumi, season with salt and pepper and turn to coat. Heat the reserved pan over medium-high heat. Cook the haloumi for 2 mins each side or until golden. Remove from the pan.',
      'Serve up: Put 3 tsp olive oil, 3 tsp red wine vinegar and 1½ tsp honey in a large bowl, season with salt and pepper and whisk to combine. Add the currants, spinach, veggies and couscous and toss to combine. Taste, then season with salt and pepper. Divide the couscous salad and haloumi among bowls and enjoy!',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm3',
    categories: [
      'c1',
      'c4'
    ],
    title: 'Asian-Style Mushroom Risotto',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://marleyspoon.com/media/recipes/165351/main_photos/large/asian_mushroom_and_ginger_risotto-04ed17fe352a5ebf271acda8aa683ce0.jpeg',
    duration: 40,
    ingredients: [
      '200g brown mushroom',
      '1 spring onion',
      '1 bunch pak choy',
      '1 ginger thump',
      '20g Asian-style stock powder',
      '150g arborio rice',
      '40g roasted cashews',
      '3 garlic cloves',
      '625ml (2.5cups) boiling water',
      '2 tsp vegetable oil',
      '2 tsp soy sauce',
      '1/2 tsp chilli flakes',
    ],
    steps: [
      'Prep ingredients: Thinly slice the spring onion. Wipe the mushrooms clean, then thinly slice. Trim the pak choy and separate the leaves. Crush or finely chop 1 garlic clove. Peel and finely grate half the ginger. Put 1 tbs Asian stock powder in a heatproof jug, add 625ml (2½ cups) boiling water and stir to dissolve.',
      'Start risotto: Heat 1 tbs vegetable oil in a medium deep frypan over medium heat. Cook the spring onion, garlic and ginger, stirring, for 3 mins or until softened. Add the mushrooms and cook, stirring, for 4 mins or until softened. Add the rice and cook, stirring, for 30 secs or until the grains are well coated.',
      'Simmer risotto: Add the stock to the pan, then reduce the heat to low and cook, covered, for 15 mins. Put the pak choy in a single layer on top of the risotto and drizzle with 2 tsp soy sauce. Cook, covered, for a further 2 mins or until most of the liquid is absorbed and the rice is almost tender. Remove the pan from the heat. Stand for 5 mins. Taste, then season with salt and pepper.',
      'Toast chilli cashews: While the risotto is standing, heat 1 tbs vegetable oil in a small frypan over medium-high heat. Toast the cashews and ½ tsp chilli flakes, tossing, for 1 min or until toasted. Remove the pan from the heat. Season with salt.',
      'Serve up: Divide the risotto and pak choy among bowls. Top with the chilli cashews and enjoy!'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),

  Meal(
    id: 'm4',
    categories: [
      'c1',
      'c3',
      'c5',
      'c7',
      'c8',
    ],
    title: 'Reduced-Carb Baja Fish Tacos',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://marleyspoon.com/media/recipes/124513/main_photos/large/reduced_carb_baja_fish_tacos-67c9f890ac567ecd43f94614b54f302c.jpeg',
    duration: 20,
    ingredients: [
      '1 red onion',
      '1 tomato',
      '1 coriander bunch',
      '5g Mexican spice blend',
      '300g basa fish fillets',
      '1 cos lettuce',
      '6 garlic cloves',
      '2 tsp white wine vinegar',
      '1 tsp olive oil',
      '2 tsp mayonnaise',
    ],
    steps: [
      'Prep ingredients: Crush garlic cloves. Finely chop the onion and tomato. Coarsely chop the coriander leaves, discarding the stems.',
      'Make pico de gallo: Combine the garlic and 2 tsp white wine vinegar in a large bowl. Add the onion, tomato and coriander, season with salt and pepper and stir to combine.',
      'Marinate fish: Combine 2 tsp Mexican spice blend (see Make it milder) and 1 tbs olive oil in a bowl and season with salt and pepper. Add the fish and turn to coat.',
      'Cook fish: Heat a medium frypan over medium-high heat. Cook the fish for 2-3 mins each side until browned and cooked through. Remove from the pan and break into large chunks.',
      'Serve up: Meanwhile, trim the lettuce, then separate the leaves. Divide the fish and pico de gallo among the lettuce cups. Drizzle with the mayonnaise and enjoy!',
    
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  
  Meal(
    id: 'm5',
    categories: [
      'c1'
      'c2',
      'c10',
    ],
    title: 'Roasted Peaches with Custard',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://marleyspoon.com/media/recipes/40600/main_photos/large/roasted-ea93fdc1981e503985f5454dbefa37d0.jpeg',
    duration: 60,
    ingredients: [
      '1 tsp maple syrup',
      '20g pistachios',
      '20g hazelnuts',
      '50g chocolate',
      '300ml cooking cream',
      '5g vanilla paste',
      '10g cornflour',
      '2 peaches',
      '2 eggs',
      '30g butter',
      '3 tbs caster sugar',
      '2 tbs plain flour',
    ],
    steps: [
      'Prepare ingredients: Read through the recipe. Line a large oven tray with baking paper. Heat the oven to 140C, fan-forced. Separate the eggs - you will need 1 egg white and 2 egg yolks (see cooking tip). Melt 20g butter and the maple syrup in a small saucepan over medium heat.',
      'Prepare wafers: Combine 1 tbs caster sugar, 2 tbs plain flour and 1 egg white in a large bowl and whisk to combine. Slowly add the melted butter mixture, whisking well. Spread the mixture thinly over the lined tray until 2mm thick. Smooth with the back of a spoon. Reserve 1 tbs pistachios for serving. Scatter with the remaining pistachios, hazelnuts and chocolate.',
      'Bake wafers: Bake the wafer for 30 mins or until golden and crisp. Lift the wafer, still on the baking paper, to a cool surface and cool for 20 mins or until crisp. Break into large pieces.',
      'Prepare custard: Meanwhile, combine the cream and vanilla in a medium saucepan, bring just to the boil over medium heat. Whisk 2 egg yolks, 1½ tbs caster sugar and 1 tsp cornflour* in a large bowl until smooth.',
      'Cook custard: Gradually whisk cream mixture into egg mixture until combined. Return the mixture to the pan and stir over medium-low heat for 3-4 mins until the custard is thickened and coats the back of a spoon. If the custard separates or curdles, whisk another egg yolk in a clean bowl. Gradually whisk curdled custard, about 1 tbs at a time, into the egg yolk until combined. Do not reheat.',
      'Get ready to serve: Halve peaches and remove stones. Sprinkle cut side with 1 tsp caster sugar. Melt 10g butter in a small frypan over medium-high heat. Cook peaches, sugared side-down, for 1 min or until caramelised. Cool slightly, then cut into wedges. Divide custard, peaches, wafers and reserved pistachios among bowls to serve.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm6',
    categories: [
      'c1',
      'c10',
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Hard,
    imageUrl:
        'https://marleyspoon.com/media/recipes/15700/main_photos/large/WEB_ADDID00002HERO_GooeyChocolateTart_033-dc73cfbe52e8a2326658216bd9fca9a4.jpg',
    duration: 50,
    ingredients: [
      '200ml cooking cream',
      '150g roasted hazelnuts',
      '1 tsp sea salt flakes',
      '300g digestive biscuits',
      '100g dark chocolate',
      '200g milk chocolate',
      '110g (1/2cup) butter',
      '100g caster sugar',
      '1 eggs',

    ],
    steps: [
      'Make tart shell: Preheat oven to 160C. Grease and line base and sides of a 22cm springform pan with baking paper. Melt 100g butter. Put half the biscuits in a food processor and process to fine crumbs (see cooking tip). Add butter and 55g (¼ cup) sugar and process until mixture resembles wet sand. Tip into pan and press firmly into base and 2.5cm up sides to form a shell.',
      'Start chocolate filling: Refrigerate tart shell for at least 10 mins to firm or until needed. Meanwhile, put the cream in a saucepan over medium heat and bring almost to the boil. Meanwhile, put the dark chocolate and milk chocolate in a heatproof bowl. Pour the warm cream over the chocolate, stand for 3 mins, then whisk until melted and combined. Cool for 5 mins.',
      'Make hazelnut praline: Meanwhile, put hazelnuts, close together, on an oven tray lined with baking paper. Put 55g (¼ cup) caster sugar in a clean small saucepan over medium-low heat. Cook, swirling pan occasionally (do not stir), for 3-5 mins until the sugar dissolves and a golden caramel forms. Working quickly, pour the caramel over the hazelnuts to coat. Set aside to cool.',
      'Finish chocolate filling: Add 1 egg and a large pinch of fine salt to the cooled chocolate mixture and whisk well to combine. Strain the chocolate mixture through a fine sieve into the tart shell.',
      'Bake tart: Bake the tart for 30 mins or until the surface has a lightly blistered appearance with a slight wobble in the centre. Remove from the oven, put on a cooling rack and set aside to cool to room temperature for at least 30-60 mins. Alternatively, it can be enjoyed while warm.',
      'Get ready to serve: Coarsely chop the hazelnut praline, then scatter over the tart. Scatter over 1 tsp sea salt flakes (reserve remainder for another use) to serve.',
      
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm7',
    categories: [
      'c1',
      'c4',
    ],
    title: 'Turkish-Style Lamb and Potato',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://marleyspoon.com/media/recipes/125922/main_photos/large/turkish_tava_lamb_and_potatoes-56119787cc3c49cdfc230611123600f2.jpeg',
    duration: 30,
    ingredients: [
      '1 onion',
      '1 potato',
      '1 capsicum',
      '1 parley bunch',
      '200g lamb mince',
      '10g Turkish seasoning',
      '4 garlic cloves',
      '1 tsp olive oil',
      '1 tsp tomato paste',
      '1  tsp honey',
      '1.5 tsp white vinegar',
    ],
    steps: [
      'Prep ingredients: Thinly slice the onion. Cut the unpeeled potato into 1cm chunks. Coarsely chop the capsicum. Coarsely chop the parsley leaves, discarding the stems. Crush or finely chop 4 garlic cloves.',
      'Brown lamb: Heat 2 tsp olive oil in a medium deep frypan over medium heat. Cook the onion, stirring, for 3-4 mins until softened. Increase the heat to high, add the lamb mince and cook, breaking up the lumps with a spoon, for 3-4 mins until well browned. Add the garlic and Turkish seasoning and cook, stirring, for 30 secs or until fragrant.',
      'Simmer lamb: Add the potato, 1 tbs tomato paste and 180ml (¾ cup) water to the lamb mixture and season with salt and pepper (see Make it yours). Bring to the boil, then reduce the heat to medium, cover and cook for 14-16 mins until the sauce is slightly thickened and the potato is tender. Taste, then season with salt and pepper.',
      'Grill capsicum: Meanwhile, preheat the grill to high. Line an oven tray with foil. Put the capsicum on the lined tray, drizzle with 2 tsp olive oil and season with salt and pepper. Grill for 6-8 mins until the capsicum is charred and tender. Transfer to a bowl. Stir in half the chopped parsley, 1 tsp honey and 1 tsp white vinegar and season with salt and pepper.',
      'Serve up: Add the remaining parsley and ½ tsp white vinegar to the lamb mixture and stir to combine. Remove the pan from the heat. Taste, then season with salt and pepper. Divide the lamb and potato among bowls, top with the capsicum mixture and enjoy!',
      'Make it yours: Boost your veggies by adding whatever you have on hand to the lamb mixture, such as green beans, broccoli or eggplant.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),

  Meal(
    id: 'm8',
    categories: [
      'c1',
      'c3',
      'c4',
    ],
    title: 'Prawn and Red Pesto Fettuccine',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://marleyspoon.com/media/recipes/155532/main_photos/large/luxe_prawn_and_pesto_fettuccine-b9395773e495bdab2f99ab37aa1850e2.jpeg',
    duration: 35,
    ingredients: [
      '20g sunflower seeds',
      '20g panko breadcrumbs',
      '200g peeled prawns',
      '325g fresh fettuccine pasta',
      '150g peas',
      '100g red pesto',
      '50g baby spinach leaves',
      '4 garlic cloves',
      '4 tbs olive oil',
    ],
    steps: [
      'Prep garlic: Bring a medium saucepan of salted water to the boil for the pasta. Crush or finely chop 4 garlic cloves.',
      'Cook pangrattato: Heat a medium deep frypan over medium heat. Cook the sunflower seeds, tossing, for 2 mins or until lightly toasted. Add 2 tsp olive oil and half the garlic and cook, stirring, for 30 secs or until fragrant. Add the breadcrumbs and cook, stirring, for 1-2 mins until golden. Remove from the pan and season with salt and pepper.',
      'Cook prawns: Heat 2 tsp olive oil in the same pan over high heat. Cook the prawns, stirring, for 2-3 mins until just cooked through. Add the remaining garlic and cook for 30 secs or until fragrant.',
      'Cook pasta and peas: Meanwhile, add three-quarters of the pasta* and the peas to the pan of boiling water. Cook, stirring occasionally, for 2 mins or until the pasta is al dente and the peas are tender. Reserve 80ml (⅓ cup) cooking water, then drain the pasta and peas.',
      'Toss pasta: Add the red pesto, spinach and pasta and peas to the prawns and toss to combine. Gradually add the reserved cooking water, stirring constantly, until the spinach is wilted and the sauce coats the pasta and looks slightly glossy. Remove the pan from the heat. Taste, then season with salt and pepper.',
      'Serve up: Divide the pasta among bowls, scatter over the pangrattato and enjoy!',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Meal(
    id: 'm9',
    categories: [
      'c1',
      'c2',
      'c3',
      'c4',
      'c7',
      'c8',
    ],
    title: 'Low-Cal Smoky Chicken',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://marleyspoon.com/media/recipes/165136/main_photos/large/low-3b89090e45218ef5a4a8f18b95fbb4cd.jpeg',
    duration: 30,
    ingredients: [
      '1 onion',
      '400g cannellini beans',
      '2 chicken-style stock cubes',
      '2 chicken breast fillets',
      '10g coriander, cumin, paprika seasoning',
      '100g baby spinach leaves',
      '4 garlic cloves',
      '180ml (¾ cup) boiling water',
      '2 tbs olive oil',
      '2 tsp tomato paste',
    
    ],
    steps: [
      'Prep ingredients: Coarsely chop the onion. Crush or finely chop 2 garlic cloves. Drain and rinse the beans. Crumble 1 stock cube* into a heatproof jug, add 180ml (¾ cup) boiling water and stir to dissolve.',
      'Prep chicken: Put the chicken breast flat on a board, put your hand on top and halve horizontally into 2 equal fillets. Season with salt and pepper.',
      'Brown chicken: Heat 1 tbs olive oil in a medium deep frypan over medium-high heat. Cook the chicken for 2-3 mins each side until browned. Remove from the pan.',
      'Make sauce: Heat 1 tbs olive oil in the same pan over medium heat. Cook the onion, stirring, for 3-4 mins until softened. Stir in the garlic, beans, stock, 1½ tsp coriander, cumin and paprika seasoning* and 2 tsp tomato paste, then bring to the boil. Reduce the heat to low and cook for 3 mins.',
      'Serve up: Add the chicken to the pan, pressing it into the sauce, and cook for a further 3-5 mins until cooked through. Add the spinach and cook for 30 secs or until wilted. Divide the chicken and bean mixture among plates and enjoy!.',
      'Make it yours: If you are not a big fan of wilted baby spinach, don\'t add it to the pan. Toss the spinach leaves in a simple vinaigrette and serve as a side salad instead.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),

  Meal(
    id: 'm10',
    categories: [
      'c1',
      'c2',
      'c3',
      'c5',
      'c6',
      'c7',
      'c8',
    ],
    title: 'Reduced-Carb Mexi Beef Meatball Slaw',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://marleyspoon.com/media/recipes/158700/main_photos/large/reduced_carb_tex_mex_baked_meatball_slaw-72e5719e4119b89825a4a79ce602d05c.jpeg',
    duration: 30,
    ingredients: [
      '300g cabbages',
      '1 capsicum',
      '1 tomato',
      '300g beef mince',
      '10g Tex-Mex seasoning',
      '20g sunflower seeds',
      '5 garlic cloves',
      '2 tsp olive oil',
      '1 tsp red or white wone vinegar',
      '2 tsp mayonaise',
      'olive oil spray (optional)',


    ],
    steps: [
      'Prep ingredients: Preheat the oven to 200C, fan-forced. Line an oven tray with baking paper. Shred the cabbage with a sharp knife or mandoline. Thinly slice the capsicum. Finely chop the tomato, then season with salt and pepper. Crush or finely chop garlic cloves.',
      'Bake meatballs: Put the beef mince, garlic and 3 tsp Tex-Mex seasoning in a large bowl and season with salt and pepper. Using damp hands, combine well, then shape into walnut-sized balls. Put the meatballs on the lined tray, spray or brush with olive oil and bake for 8-10 mins until cooked through.',
      'Toast sunflower seeds: Meanwhile, put the sunflower seeds in a cold small frypan over medium heat. Toast, tossing, for 3-4 mins until evenly golden. Remove from the pan and cool slightly.',
      'Make slaw: Combine 2 tsp olive oil and 1 tsp red wine vinegar in a large bowl and season with salt and pepper. Add the cabbage and capsicum and gently massage for 30 secs or until slightly softened',
      'Serve up: Combine the remaining Tex-Mex seasoning, 2 tbs mayonnaise and 1 tsp water in a bowl. Divide the slaw, meatballs and tomato among plates. Scatter with the sunflower seeds and spoon over the Tex-Mex mayo. Enjoy!',
      'Kitchen 101: It may sound strange to massage your food but it helps to break down the tough fibres, making the cabbage and capsicum tender and easier to eat.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
];

